### ISSUE TITLE
Interactive Use Case #1:  Infrared Analysis Around Indian Point

### ISSUE THREAD

**Issue by bfreeds** [MaptimeNYC/working-with-satellite-data#3]
This should be a simple step-by-step demo of using Landsat data in Google Earth Engine.  Need to figure out if we can see thermal plumes from the radiation in the water around Indian Point.  Any good academic resources to guide the analysis would be great.

**Comment by bfreeds** [comment]
The structure of this demo should be parallel to the structure of #4.

**Comment by berylsinc** [comment]
@bfreeds A couple things to look at.
[2007_11 Entrainment, Impingement and Thermal Impacts at Indian Point.pdf](https://github.com/MaptimeNYC/working-with-satellite-data/files/692283/2007_11.Entrainment.Impingement.and.Thermal.Impacts.at.Indian.Point.pdf)
[1969_02 ConEd Thermal Pollution Report.pdf](https://github.com/MaptimeNYC/working-with-satellite-data/files/692279/1969_02.ConEd.Thermal.Pollution.Report.pdf)

**Comment by bfreeds** [comment]
Thanks @berylsinc!  Those are both great resources.  I'm also looking into the steps to take to show temperature.  

Here's what I'm seeing so far:
- ["Coastal sea surface temperature variability from Landsat infrared data" Thomas et al., 2002](http://wvvw.gulfofmaine.org/kb/uploads/14137/ThomasEtAl02.pdf)
- ["Deriving Temperature from Landsat 8 Thermal Bands TIRS" -ESRI Blog](https://blogs.esri.com/esri/arcgis/2014/01/06/deriving-temperature-from-landsat-8-thermal-bands-tirs/)

**Comment by berylsinc** [comment]
TIRS Requirements http://landsat.gsfc.nasa.gov/tirs-requirements/
